### PR TITLE
get content type from filename

### LINKED ISSUE #1: doesn't serve file when expected
i was experiencing a problem where the library was not working as expected to serve a file that was clearly present/being requested. i was able to fix the issue locally by modifying line 98 of /src/utils.ts:

```js
      (contentType(pathFile.replace("/", "\\")) || "application/octet-stream"),
```

i changed it to:

```js
      (contentType(pathFile.replaceAll("/", "")) || "application/octet-stream"),
```

and it began to work. however, i'm not sure this is really the best fix. the real problem, it seems to me, is that it is calling `contentType` on `pathFile` (the full absolute file path) rather than just the filename (`index.js` or whatever).

### PR DESCRIPTION
**Pull request by peetklecha**
Fixes #1

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -95,7 +96,7 @@ export async function sendFile(
   headers.set(
     "Content-Type",
     headers.get("Content-Type") ||
-      (contentType(pathFile.replace("/", "\\")) || "application/octet-stream"),
+      (contentType(path.replace("/", "\\")) || "application/octet-stream"),
```
Comment (herudi) [inline src/utils.ts:99]: this point if accessing the root folder or accessing the default index then it is undefined. because the path does not include the filename if accessing the root folder. i agree with this one `pathFile.replace("/", "")`. What do you think ?

**Comment by herudi** [comment]
@peetklecha  ok, thanks for contrib. now, fix in 1.1.2 and support deno > 1.16.x (deno std http).
```ts
import { serve } from "https://deno.land/std@0.116.0/http/server.ts";
import staticFiles from "https://deno.land/x/static_files@1.1.2/mod.ts";

const serveFiles = (req: Request) => staticFiles('public')({ 
    request: req, 
    respondWith: (r: Response) => r 
})

serve((req) => serveFiles(req), { addr: ':3000' });
```
